### ISSUE TITLE
add test for SDXL in our pipelines

### ISSUE THREAD

**Issue by noskill** [singnet/metafusion#24]
https://huggingface.co/docs/diffusers/api/pipelines/stable_diffusion/stable_diffusion_xl

**Comment by noskill** [comment]
also typing might be wrong in some places since StableDiffusionXLPipeline doesn't inherit from StableDiffusionPipeline

**Comment by Necr0x0Der** [comment]
The test is added in #29 , but it should not work normally since `XL` should be used inside all `StableDiffusion ... Pipeline` class names for SDXL models to load correctly (with the current pip version of diffusers). This issue can be closed as formally completed, but then another issue should be created on adding support for SDXL models in our pipes.
